import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Nav
  'nav.home': { fr: 'Accueil', en: 'Home', es: 'Inicio' },
  'nav.story': { fr: 'Notre Histoire', en: 'Our Story', es: 'Nuestra Historia' },
  'nav.details': { fr: 'Détails', en: 'Details', es: 'Detalles' },
  'nav.rsvp': { fr: 'RSVP', en: 'RSVP', es: 'RSVP' },
  'nav.gallery': { fr: 'Galerie', en: 'Gallery', es: 'Galería' },
  'nav.registry': { fr: 'Cadeaux', en: 'Gifts', es: 'Regalos' },

  // Hero
  'hero.date': { fr: '___________', en: '___________', es: '___________' },
  'hero.tagline': { fr: 'Nous nous marions !', en: 'We\'re getting married!', es: '¡Nos casamos!' },
  'hero.cta': { fr: 'Confirmer votre présence', en: 'RSVP Now', es: 'Confirmar asistencia' },
  'hero.scroll': { fr: 'Découvrir plus', en: 'Discover more', es: 'Descubrir más' },

  // Countdown
  'countdown.days': { fr: 'Jours', en: 'Days', es: 'Días' },
  'countdown.hours': { fr: 'Heures', en: 'Hours', es: 'Horas' },
  'countdown.minutes': { fr: 'Minutes', en: 'Minutes', es: 'Minutos' },
  'countdown.seconds': { fr: 'Secondes', en: 'Seconds', es: 'Segundos' },

  // Index page
  'index.ourJourney': { fr: 'Notre Parcours', en: 'Our Journey', es: 'Nuestro Camino' },
  'index.joinCelebration': { fr: 'Rejoignez la célébration', en: 'Join our celebration', es: 'Únete a la celebración' },
  'index.celebrationDesc': { fr: 'Une célébration d\'amour, de famille et d\'union', en: 'A celebration of love, family & togetherness', es: 'Una celebración de amor, familia y unión' },
  'index.guestsInvited': { fr: 'Invités', en: 'Guests Invited', es: 'Invitados' },
  'index.courseDinner': { fr: 'Plats au Dîner', en: 'Course Dinner', es: 'Platos de Cena' },
  'index.love': { fr: 'Amour', en: 'Love', es: 'Amor' },
  'index.explore': { fr: 'Explorer', en: 'Explore', es: 'Explorar' },
  'index.capturedMoments': { fr: 'Des moments précieux de notre histoire d\'amour', en: 'Captured moments of our love story', es: 'Momentos capturados de nuestra historia de amor' },

  // Story
  'story.title': { fr: 'Notre Histoire', en: 'Our Story', es: 'Nuestra Historia' },
  'story.subtitle': { fr: 'Le chemin qui nous a menés l\'un vers l\'autre', en: 'The journey that led us to each other', es: 'El camino que nos llevó el uno al otro' },
  'story.event1.title': { fr: '___________', en: '___________', es: '___________' },
  'story.event1.description': { fr: '___________', en: '___________', es: '___________' },
  'story.event1.date': { fr: '___________', en: '___________', es: '___________' },
  'story.event2.title': { fr: '___________', en: '___________', es: '___________' },
  'story.event2.description': { fr: '___________', en: '___________', es: '___________' },
  'story.event2.date': { fr: '___________', en: '___________', es: '___________' },
  'story.event3.title': { fr: '___________', en: '___________', es: '___________' },
  'story.event3.description': { fr: '___________', en: '___________', es: '___________' },
  'story.event3.date': { fr: '___________', en: '___________', es: '___________' },
  'story.event4.title': { fr: '___________', en: '___________', es: '___________' },
  'story.event4.description': { fr: '___________', en: '___________', es: '___________' },
  'story.event4.date': { fr: '___________', en: '___________', es: '___________' },
  'story.event5.title': { fr: '___________', en: '___________', es: '___________' },
  'story.event5.description': { fr: '___________', en: '___________', es: '___________' },
  'story.event5.date': { fr: '___________', en: '___________', es: '___________' },
  'story.continues': { fr: 'Notre aventure continue...', en: 'Our journey continues...', es: 'Nuestra aventura continúa...' },

  // Details
  'details.title': { fr: 'Détails du Mariage', en: 'Wedding Details', es: 'Detalles de la Boda' },
  'details.subtitle': { fr: 'Tout ce que vous devez savoir pour cette journée spéciale', en: 'Everything you need to know for this special day', es: 'Todo lo que necesitas saber para este día especial' },
  'details.ceremony': { fr: 'Cérémonie', en: 'Ceremony', es: 'Ceremonia' },
  'details.ceremony.time': { fr: '___________', en: '___________', es: '___________' },
  'details.ceremony.location': { fr: '___________', en: '___________', es: '___________' },
  'details.ceremony.address': { fr: '___________', en: '___________', es: '___________' },
  'details.reception': { fr: 'Réception', en: 'Reception', es: 'Recepción' },
  'details.reception.time': { fr: '___________', en: '___________', es: '___________' },
  'details.reception.location': { fr: '___________', en: '___________', es: '___________' },
  'details.reception.address': { fr: '___________', en: '___________', es: '___________' },
  'details.accommodation': { fr: 'Hébergement', en: 'Accommodation', es: 'Alojamiento' },
  'details.accommodation.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.accommodation.hotel': { fr: '___________', en: '___________', es: '___________' },
  'details.accommodation.hotel.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.accommodation.address': { fr: 'Adresse', en: 'Address', es: 'Dirección' },
  'details.accommodation.address.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.accommodation.rate': { fr: 'Tarif spécial', en: 'Special Rate', es: 'Tarifa especial' },
  'details.accommodation.rate.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.transport': { fr: 'Transport', en: 'Transportation', es: 'Transporte' },
  'details.transport.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.transport.shuttle': { fr: 'Navette', en: 'Shuttle Service', es: 'Servicio de transporte' },
  'details.transport.shuttle.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.transport.parking': { fr: 'Stationnement', en: 'Parking', es: 'Estacionamiento' },
  'details.transport.parking.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.transport.schedule': { fr: 'Horaires navette', en: 'Shuttle Schedule', es: 'Horario del transporte' },
  'details.transport.schedule.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.tapToSee': { fr: 'Appuyez pour voir', en: 'Tap to view', es: 'Toca para ver' },

  // Ceremony program
  'details.ceremony.program.welcome': { fr: '___________', en: '___________', es: '___________' },
  'details.ceremony.program.readings': { fr: 'Lectures Bibliques', en: 'Scripture Readings', es: 'Lecturas Bíblicas' },
  'details.ceremony.program.readings.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.ceremony.program.vows': { fr: 'Échange des Vœux', en: 'Exchange of Vows', es: 'Intercambio de Votos' },
  'details.ceremony.program.vows.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.ceremony.program.hymns': { fr: 'Cantiques', en: 'Hymns', es: 'Himnos' },
  'details.ceremony.program.hymns.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.ceremony.program.blessing': { fr: 'Bénédiction Finale', en: 'Final Blessing', es: 'Bendición Final' },
  'details.ceremony.program.blessing.desc': { fr: '___________', en: '___________', es: '___________' },

  // Reception program
  'details.reception.program.cocktail': { fr: '___________', en: '___________', es: '___________' },
  'details.reception.program.dinner': { fr: 'Dîner', en: 'Dinner', es: 'Cena' },
  'details.reception.program.dinner.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.reception.program.dance': { fr: 'Soirée Dansante', en: 'Dancing', es: 'Baile' },
  'details.reception.program.dance.desc': { fr: '___________', en: '___________', es: '___________' },
  'details.reception.program.cake': { fr: 'Gâteau de Mariage', en: 'Wedding Cake', es: 'Pastel de Bodas' },
  'details.reception.program.cake.desc': { fr: '___________', en: '___________', es: '___________' },

  // RSVP
  'rsvp.title': { fr: 'Confirmer votre Présence', en: 'Confirm your Attendance', es: 'Confirma tu Asistencia' },
  'rsvp.subtitle': { fr: 'Nous avons hâte de célébrer avec vous', en: 'We can\'t wait to celebrate with you', es: 'No podemos esperar para celebrar contigo' },
  'rsvp.name': { fr: 'Votre nom complet', en: 'Your Full Name', es: 'Tu Nombre Completo' },
  'rsvp.name.placeholder': { fr: 'Prénom et nom', en: 'First and last name', es: 'Nombre y apellido' },
  'rsvp.email': { fr: 'Votre email', en: 'Your Email', es: 'Tu Correo' },
  'rsvp.email.placeholder': { fr: 'email@exemple.com', en: 'email@example.com', es: 'correo@ejemplo.com' },
  'rsvp.attending': { fr: 'Serez-vous présent(e) ?', en: 'Will you attend?', es: '¿Asistirás?' },
  'rsvp.yes': { fr: 'Avec joie !', en: 'Joyfully!', es: '¡Con alegría!' },
  'rsvp.no': { fr: 'Malheureusement non', en: 'Unfortunately no', es: 'Lamentablemente no' },
  'rsvp.meal': { fr: 'Votre plat principal', en: 'Your Main Course', es: 'Tu Plato Principal' },
  'rsvp.cuisine': { fr: 'Choisissez votre cuisine', en: 'Choose Your Cuisine', es: 'Elige Tu Cocina' },
  'rsvp.cuisine.african': { fr: 'Africaine', en: 'African', es: 'Africana' },
  'rsvp.cuisine.indian': { fr: 'Indienne', en: 'Indian', es: 'India' },
  'rsvp.cuisine.italian': { fr: 'Italienne', en: 'Italian', es: 'Italiana' },
  'rsvp.cuisine.french': { fr: 'Française', en: 'French', es: 'Francesa' },
  'rsvp.cuisine.mediterranean': { fr: 'Méditerranéenne', en: 'Mediterranean', es: 'Mediterránea' },
  'rsvp.cuisine.caribbean': { fr: 'Caribéenne', en: 'Caribbean', es: 'Caribeña' },
  // African dishes
  'rsvp.meal.jollof': { fr: 'Riz Jollof', en: 'Jollof Rice', es: 'Arroz Jollof' },
  'rsvp.meal.grilled_tilapia': { fr: 'Tilapia Grillé', en: 'Grilled Tilapia', es: 'Tilapia a la Parrilla' },
  'rsvp.meal.veg_african': { fr: 'Végétarien Africain', en: 'African Vegetarian', es: 'Vegetariano Africano' },
  'rsvp.meal.ndole': { fr: 'Ndolé', en: 'Ndolé', es: 'Ndolé' },
  // Indian dishes
  'rsvp.meal.butter_chicken': { fr: 'Poulet Beurre', en: 'Butter Chicken', es: 'Pollo con Mantequilla' },
  'rsvp.meal.paneer_tikka': { fr: 'Paneer Tikka', en: 'Paneer Tikka', es: 'Paneer Tikka' },
  'rsvp.meal.dal_makhani': { fr: 'Dal Makhani', en: 'Dal Makhani', es: 'Dal Makhani' },
  'rsvp.meal.biryani': { fr: 'Biryani', en: 'Biryani', es: 'Biryani' },
  // Italian dishes
  'rsvp.meal.risotto': { fr: 'Risotto', en: 'Risotto', es: 'Risotto' },
  'rsvp.meal.osso_buco': { fr: 'Osso Buco', en: 'Osso Buco', es: 'Osso Buco' },
  'rsvp.meal.eggplant_parm': { fr: 'Aubergine Parmigiana', en: 'Eggplant Parmigiana', es: 'Berenjena a la Parmesana' },
  'rsvp.meal.seafood_linguine': { fr: 'Linguine Fruits de Mer', en: 'Seafood Linguine', es: 'Linguine con Mariscos' },
  // French dishes
  'rsvp.meal.coq_au_vin': { fr: 'Coq au Vin', en: 'Coq au Vin', es: 'Coq au Vin' },
  'rsvp.meal.ratatouille': { fr: 'Ratatouille', en: 'Ratatouille', es: 'Ratatouille' },
  'rsvp.meal.salmon_en_croute': { fr: 'Saumon en Croûte', en: 'Salmon en Croûte', es: 'Salmón en Croûte' },
  'rsvp.meal.beef_bourguignon': { fr: 'Bœuf Bourguignon', en: 'Beef Bourguignon', es: 'Bœuf Bourguignon' },
  // Mediterranean dishes
  'rsvp.meal.lamb_kofta': { fr: 'Kofta d\'Agneau', en: 'Lamb Kofta', es: 'Kofta de Cordero' },
  'rsvp.meal.falafel_plate': { fr: 'Assiette Falafel', en: 'Falafel Plate', es: 'Plato de Falafel' },
  'rsvp.meal.grilled_sea_bass': { fr: 'Bar Grillé', en: 'Grilled Sea Bass', es: 'Lubina a la Parrilla' },
  'rsvp.meal.stuffed_peppers': { fr: 'Poivrons Farcis', en: 'Stuffed Peppers', es: 'Pimientos Rellenos' },
  // Caribbean dishes
  'rsvp.meal.jerk_chicken': { fr: 'Poulet Jerk', en: 'Jerk Chicken', es: 'Pollo Jerk' },
  'rsvp.meal.curry_goat': { fr: 'Curry de Chèvre', en: 'Curry Goat', es: 'Curry de Cabra' },
  'rsvp.meal.fish_escovitch': { fr: 'Poisson Escovitch', en: 'Escovitch Fish', es: 'Pescado Escovitch' },
  'rsvp.meal.callaloo_veg': { fr: 'Callaloo Végétarien', en: 'Callaloo Veggie', es: 'Callaloo Vegetariano' },
  // Meal notice
  'rsvp.meal.notice.title': { fr: 'Notre engagement pour une célébration sainte', en: 'Our commitment to a holy celebration', es: 'Nuestro compromiso con una celebración santa' },
  'rsvp.meal.notice.body': { fr: 'En accord avec nos valeurs chrétiennes, nous ne servons pas d\'alcool (bière, vin, spiritueux) ni de viande non biblique (porc, crustacés, etc.). Tous nos plats sont préparés selon les principes alimentaires bibliques. Merci de votre compréhension. 🙏', en: 'In accordance with our Christian values, we do not serve alcohol (beer, wine, spirits) or non-biblical meats (pork, shellfish, etc.). All our dishes are prepared following biblical dietary principles. Thank you for your understanding. 🙏', es: 'De acuerdo con nuestros valores cristianos, no servimos alcohol (cerveza, vino, licores) ni carnes no bíblicas (cerdo, mariscos, etc.). Todos nuestros platos se preparan siguiendo los principios dietéticos bíblicos. Gracias por su comprensión. 🙏' },
  // Drinks
  'rsvp.drinks': { fr: 'Vos boissons', en: 'Your Drinks', es: 'Tus Bebidas' },
  'rsvp.drinks.notice': { fr: '🚫 Pas d\'alcool — uniquement des boissons non alcoolisées pour honorer notre célébration', en: '🚫 No alcohol — only non-alcoholic beverages to honor our celebration', es: '🚫 Sin alcohol — solo bebidas sin alcohol para honrar nuestra celebración' },
  'rsvp.drink.juice_tropical': { fr: 'Jus Tropical', en: 'Tropical Juice', es: 'Jugo Tropical' },
  'rsvp.drink.lemonade': { fr: 'Citronnade', en: 'Lemonade', es: 'Limonada' },
  'rsvp.drink.sparkling_water': { fr: 'Eau Pétillante', en: 'Sparkling Water', es: 'Agua con Gas' },
  'rsvp.drink.mocktail': { fr: 'Mocktail', en: 'Mocktail', es: 'Mocktail' },
  'rsvp.drink.tea': { fr: 'Thé', en: 'Tea', es: 'Té' },
  'rsvp.drink.coffee': { fr: 'Café', en: 'Coffee', es: 'Café' },
  'rsvp.drink.smoothie': { fr: 'Smoothie', en: 'Smoothie', es: 'Smoothie' },
  'rsvp.drink.hibiscus': { fr: 'Bissap / Hibiscus', en: 'Hibiscus Drink', es: 'Bebida de Hibisco' },
  'rsvp.done.drinks': { fr: 'Vos boissons', en: 'Your Drinks', es: 'Tus Bebidas' },
  'rsvp.sides': { fr: 'Accompagnements', en: 'Side Dishes', es: 'Acompañamientos' },
  'rsvp.side.potatoes': { fr: 'Pommes de terre', en: 'Potatoes', es: 'Papas' },
  'rsvp.side.vegetables': { fr: 'Légumes grillés', en: 'Grilled Vegetables', es: 'Verduras a la Parrilla' },
  'rsvp.side.rice': { fr: 'Riz parfumé', en: 'Fragrant Rice', es: 'Arroz Aromático' },
  'rsvp.side.salad': { fr: 'Salade verte', en: 'Green Salad', es: 'Ensalada Verde' },
  'rsvp.side.quinoa': { fr: 'Quinoa', en: 'Quinoa', es: 'Quinoa' },
  'rsvp.side.pasta': { fr: 'Pâtes fraîches', en: 'Fresh Pasta', es: 'Pasta Fresca' },
  'rsvp.side.couscous': { fr: 'Couscous', en: 'Couscous', es: 'Cuscús' },
  'rsvp.side.fries': { fr: 'Frites', en: 'Fries', es: 'Papas Fritas' },
  'rsvp.side.sweetpotato': { fr: 'Patate douce', en: 'Sweet Potato', es: 'Camote' },
  'rsvp.side.hummus': { fr: 'Houmous & crudités', en: 'Hummus & Veggies', es: 'Hummus y Verduras' },
  'rsvp.side.plantain': { fr: 'Plantain frit', en: 'Fried Plantain', es: 'Plátano Frito' },
  'rsvp.side.cassava': { fr: 'Manioc', en: 'Cassava', es: 'Yuca' },
  'rsvp.side.naan': { fr: 'Pain Naan', en: 'Naan Bread', es: 'Pan Naan' },
  'rsvp.side.raita': { fr: 'Raïta', en: 'Raita', es: 'Raita' },
  'rsvp.side.bread': { fr: 'Pain artisanal', en: 'Artisan Bread', es: 'Pan Artesanal' },
  'rsvp.side.polenta': { fr: 'Polenta', en: 'Polenta', es: 'Polenta' },
  'rsvp.dietary': { fr: 'Restrictions alimentaires', en: 'Dietary Restrictions', es: 'Restricciones Alimentarias' },
  'rsvp.dietary.placeholder': { fr: 'Allergies, régime spécial...', en: 'Allergies, special diet...', es: 'Alergias, dieta especial...' },
  'rsvp.table.anonymous': { fr: 'Rester anonyme', en: 'Stay anonymous', es: 'Permanecer anónimo' },
  'rsvp.table.anonymous.hint': { fr: 'Votre nom sera affiché comme « Anonyme »', en: 'Your name will appear as "Anonymous"', es: 'Tu nombre aparecerá como "Anónimo"' },
  'rsvp.table.seats.available': { fr: 'places disponibles', en: 'seats available', es: 'asientos disponibles' },
  'rsvp.table.full': { fr: 'Complet', en: 'Full', es: 'Lleno' },
  'rsvp.table.leave': { fr: 'Quitter', en: 'Leave', es: 'Salir' },
  'rsvp.table.join': { fr: 'Rejoindre', en: 'Join', es: 'Unirse' },
  'rsvp.table.search': { fr: 'Rechercher une table...', en: 'Search for a table...', es: 'Buscar una mesa...' },
  'rsvp.table.filter.all': { fr: 'Toutes', en: 'All', es: 'Todas' },
  'rsvp.table.filter.available': { fr: 'Disponibles', en: 'Available', es: 'Disponibles' },
  'rsvp.table.filter.full': { fr: 'Complètes', en: 'Full', es: 'Llenas' },
  'rsvp.table.summary': { fr: '{available} tables disponibles · {full} complètes sur {total}', en: '{available} available · {full} full out of {total} tables', es: '{available} disponibles · {full} llenas de {total} mesas' },
  'rsvp.plusone': { fr: 'Accompagnant(e)', en: 'Plus One', es: 'Acompañante' },
  'rsvp.plusone.name': { fr: 'Nom de l\'accompagnant(e)', en: 'Plus one\'s name', es: 'Nombre del acompañante' },
  'rsvp.companions': { fr: 'Accompagnants', en: 'Companions', es: 'Acompañantes' },
  'rsvp.companions.hint': { fr: 'Ajoutez les noms des personnes qui vous accompagnent', en: 'Add the names of people coming with you', es: 'Agrega los nombres de las personas que te acompañan' },
  'rsvp.companions.placeholder': { fr: 'Nom complet de l\'accompagnant', en: 'Companion\'s full name', es: 'Nombre completo del acompañante' },
  'rsvp.companions.add': { fr: 'Ajouter', en: 'Add', es: 'Agregar' },
  'rsvp.companions.count': { fr: '{count} personnes au total (vous inclus)', en: '{count} people total (including you)', es: '{count} personas en total (incluido tú)' },
  'rsvp.submit': { fr: 'Confirmer', en: 'Confirm', es: 'Confirmar' },
  'rsvp.next': { fr: 'Suivant', en: 'Next', es: 'Siguiente' },
  'rsvp.back': { fr: 'Retour', en: 'Back', es: 'Atrás' },
  'rsvp.step.info': { fr: 'Vos informations', en: 'Your Information', es: 'Tu Información' },
  'rsvp.step.info.hint': { fr: 'Quelques détails pour vous identifier', en: 'A few details to identify you', es: 'Algunos detalles para identificarte' },
  'rsvp.step.meal': { fr: 'Composez votre repas', en: 'Design Your Meal', es: 'Diseña Tu Comida' },
  'rsvp.step.meal.hint': { fr: 'Choisissez votre plat et accompagnements', en: 'Pick your main course and sides', es: 'Elige tu plato principal y acompañamientos' },
  'rsvp.step.table': { fr: 'Choisissez votre table', en: 'Choose Your Table', es: 'Elige Tu Mesa' },
  'rsvp.step.table.hint': { fr: 'Rejoignez vos amis ou créez une table famille', en: 'Join your friends or create a family table', es: 'Únete a tus amigos o crea una mesa familiar' },
  'rsvp.step.gift': { fr: 'Un cadeau ?', en: 'A Gift?', es: '¿Un Regalo?' },
  'rsvp.step.gift.hint': { fr: 'Optionnel — votre présence est déjà un cadeau', en: 'Optional — your presence is already a gift', es: 'Opcional — tu presencia ya es un regalo' },
  'rsvp.gift.message': { fr: 'Votre présence est notre plus beau cadeau. Si vous souhaitez contribuer, scannez le QR code ou copiez le lien de paiement.', en: 'Your presence is our greatest gift. If you wish to contribute, scan the QR code or copy the payment link.', es: 'Tu presencia es nuestro mayor regalo. Si deseas contribuir, escanea el código QR o copia el enlace de pago.' },
  'rsvp.gift.scanQR': { fr: 'Scannez ce code pour envoyer votre cadeau', en: 'Scan this code to send your gift', es: 'Escanea este código para enviar tu regalo' },
  'rsvp.gift.copyLink': { fr: 'Copier le lien', en: 'Copy payment link', es: 'Copiar enlace de pago' },
  'rsvp.gift.copied': { fr: 'Lien copié !', en: 'Link copied!', es: '¡Enlace copiado!' },
  'rsvp.gift.generateQR': { fr: 'QR Code', en: 'QR Code', es: 'Código QR' },
  'rsvp.gift.skip': { fr: 'Passer & confirmer', en: 'Skip & confirm', es: 'Omitir y confirmar' },
  'rsvp.gift.changeAmount': { fr: 'Changer le montant', en: 'Change amount', es: 'Cambiar monto' },
  'rsvp.gift.noteLabel': { fr: 'Un petit mot (optionnel)', en: 'A short note (optional)', es: 'Una nota breve (opcional)' },
  'rsvp.done.meal': { fr: 'Votre repas', en: 'Your Meal', es: 'Tu Comida' },
  'rsvp.done.gift': { fr: 'Votre cadeau', en: 'Your Gift', es: 'Tu Regalo' },
  'rsvp.done.confirmation': { fr: 'Un email de confirmation vous sera envoyé prochainement.', en: 'A confirmation email will be sent to you shortly.', es: 'Un correo de confirmación se enviará pronto.' },
  'rsvp.table.label': { fr: 'Table', en: 'Table', es: 'Mesa' },
  'rsvp.table.createFamily': { fr: 'Table famille', en: 'Family Table', es: 'Mesa Familiar' },
  'rsvp.table.familyName': { fr: 'Nom de la table', en: 'Table Name', es: 'Nombre de la Mesa' },
  'rsvp.table.familyName.placeholder': { fr: 'Ex: Famille Martin', en: 'E.g. The Smiths', es: 'Ej: Familia García' },
  'rsvp.table.yourSeat': { fr: 'Votre place', en: 'Your seat', es: 'Tu asiento' },
  'rsvp.done.title': { fr: 'Merci !', en: 'Thank You!', es: '¡Gracias!' },
  'rsvp.done.attending': { fr: 'Votre réponse a été enregistrée. Nous avons hâte de vous voir !', en: 'Your response has been recorded. We can\'t wait to see you!', es: '¡Tu respuesta ha sido registrada. No podemos esperar para verte!' },
  'rsvp.done.notattending': { fr: 'Nous sommes désolés que vous ne puissiez pas venir. Vous serez dans nos pensées.', en: 'We\'re sorry you can\'t make it. You\'ll be in our thoughts.', es: 'Lamentamos que no puedas asistir. Estarás en nuestros pensamientos.' },
  'rsvp.done.table': { fr: 'Votre table', en: 'Your Table', es: 'Tu Mesa' },

  // Gallery
  'gallery.title': { fr: 'Notre Galerie', en: 'Our Gallery', es: 'Nuestra Galería' },
  'gallery.subtitle': { fr: 'Des moments précieux capturés en images', en: 'Precious moments captured in images', es: 'Momentos preciosos capturados en imágenes' },

  // Registry
  'registry.title': { fr: 'Cadeaux', en: 'Gifts', es: 'Regalos' },
  'registry.subtitle': { fr: 'Votre présence est notre plus beau cadeau', en: 'Your presence is our greatest gift', es: 'Tu presencia es nuestro mayor regalo' },
  'registry.message': { fr: 'Si vous souhaitez nous gâter, vous pouvez contribuer à notre nouvelle vie ensemble. Chaque geste compte énormément.', en: 'If you wish to spoil us, you can contribute to our new life together. Every gesture means the world.', es: 'Si deseas consentirmos, puedes contribuir a nuestra nueva vida juntos. Cada gesto significa mucho.' },
  'registry.link': { fr: 'Voir la liste', en: 'View Registry', es: 'Ver Registro' },
  'registry.tier.bouquet': { fr: 'Bouquet de fleurs', en: 'Flower Bouquet', es: 'Ramo de Flores' },
  'registry.tier.toast': { fr: 'Toast des mariés', en: 'Wedding Toast', es: 'Brindis de Boda' },
  'registry.tier.sparkle': { fr: 'Étoile filante', en: 'Shooting Star', es: 'Estrella Fugaz' },
  'registry.tier.diamond': { fr: 'Diamant', en: 'Diamond', es: 'Diamante' },
  'registry.custom': { fr: 'Montant personnalisé', en: 'Custom Amount', es: 'Monto Personalizado' },
  'registry.custom.placeholder': { fr: 'Montant', en: 'Amount', es: 'Monto' },
  'registry.give': { fr: 'Offrir', en: 'Give', es: 'Dar' },
  'registry.animalfund': { fr: 'Fonds pour les animaux', en: 'Animal Fund', es: 'Fondo para Animales' },
  'registry.animalfund.desc': { fr: 'Contribuer à notre amour pour les animaux', en: 'Contribute to our love for animals', es: 'Contribuir a nuestro amor por los animales' },
  'registry.dialog.title': { fr: 'Offrir un cadeau', en: 'Send a Gift', es: 'Enviar un Regalo' },
  'registry.dialog.subtitle': { fr: 'Votre générosité nous touche profondément', en: 'Your generosity touches us deeply', es: 'Tu generosidad nos conmueve profundamente' },
  'registry.dialog.amount': { fr: 'Montant du cadeau', en: 'Gift Amount', es: 'Monto del Regalo' },
  'registry.dialog.name': { fr: 'Votre nom', en: 'Your Name', es: 'Tu Nombre' },
  'registry.dialog.name.placeholder': { fr: 'Prénom et nom', en: 'First and last name', es: 'Nombre y apellido' },
  'registry.dialog.message': { fr: 'Un petit mot (optionnel)', en: 'A short message (optional)', es: 'Un mensaje breve (opcional)' },
  'registry.dialog.message.placeholder': { fr: 'Félicitations aux mariés...', en: 'Congratulations to the couple...', es: 'Felicidades a los novios...' },
  'registry.dialog.send': { fr: 'Envoyer le cadeau', en: 'Send Gift', es: 'Enviar Regalo' },
  'registry.dialog.thanks': { fr: 'Merci pour votre générosité !', en: 'Thank you for your generosity!', es: '¡Gracias por tu generosidad!' },
  'registry.dialog.note': { fr: 'Le paiement sera configuré prochainement. Merci de votre patience.', en: 'Payment will be configured soon. Thank you for your patience.', es: 'El pago se configurará pronto. Gracias por tu paciencia.' },

  // Explore
  'explore.title': { fr: 'Découvrez Notre Mariage', en: 'Explore Our Wedding', es: 'Explora Nuestra Boda' },
  'explore.subtitle': { fr: 'Tout ce que vous devez savoir', en: 'Everything you need to know', es: 'Todo lo que necesitas saber' },

  // Love language
  'love.tagline': { fr: 'Deux cœurs, une seule âme', en: 'Two hearts, one soul', es: 'Dos corazones, una sola alma' },
  'love.intro': { fr: '___________', en: '___________', es: '___________' },
  'love.quote1': { fr: '"Je t\'ai aimé d\'un amour éternel, c\'est pourquoi je te conserve ma bonté."', en: '"I have loved you with an everlasting love; therefore I have continued my faithfulness to you."', es: '"Con amor eterno te he amado; por eso te sigo con fidelidad."' },
  'love.quote1.ref': { fr: 'Jérémie 31:3', en: 'Jeremiah 31:3', es: 'Jeremías 31:3' },
  'love.quote1.text': { fr: 'Je t\'ai aimé d\'un amour éternel, c\'est pourquoi je te conserve ma bonté.', en: 'I have loved you with an everlasting love; therefore I have continued my faithfulness to you.', es: 'Con amor eterno te he amado; por eso te sigo con fidelidad.' },
  'announcements.title': { fr: 'Annonces', en: 'Announcements', es: 'Anuncios' },
  'dashboard.announcements': { fr: 'Annonces', en: 'Announcements', es: 'Anuncios' },
  'dashboard.newAnnouncement': { fr: 'Nouvelle annonce', en: 'New Announcement', es: 'Nuevo Anuncio' },
  'dashboard.announcementTitle': { fr: 'Titre', en: 'Title', es: 'Título' },
  'dashboard.announcementContent': { fr: 'Contenu', en: 'Content', es: 'Contenido' },
  'dashboard.post': { fr: 'Publier', en: 'Post', es: 'Publicar' },
  'dashboard.noAnnouncements': { fr: 'Aucune annonce pour le moment', en: 'No announcements yet', es: 'Sin anuncios por ahora' },
  'dashboard.deleteConfirm': { fr: 'Supprimer ?', en: 'Delete?', es: '¿Eliminar?' },
  'dashboard.quotes': { fr: 'Citations', en: 'Quotes', es: 'Citas' },
  'dashboard.newQuote': { fr: 'Nouvelle citation', en: 'New Quote', es: 'Nueva Cita' },
  'dashboard.quotePlaceholder': { fr: 'Écrivez votre citation ou pensée personnelle...', en: 'Write your personal quote or thought...', es: 'Escribe tu cita o pensamiento personal...' },
  'dashboard.noQuotes': { fr: 'Aucune citation pour le moment', en: 'No quotes yet', es: 'Sin citas por ahora' },
  'love.promise': { fr: 'Notre promesse d\'amour éternel', en: 'Our promise of everlasting love', es: 'Nuestra promesa de amor eterno' },
  'love.promise.desc': { fr: 'Devant Dieu et nos proches, nous nous promettons un amour fidèle, patient et éternel.', en: 'Before God and our loved ones, we promise each other a faithful, patient, and eternal love.', es: 'Ante Dios y nuestros seres queridos, nos prometemos un amor fiel, paciente y eterno.' },
  'love.soulmates': { fr: 'Âmes sœurs par la grâce de Dieu', en: 'Soulmates by the grace of God', es: 'Almas gemelas por la gracia de Dios' },
  'love.together': { fr: 'Ensemble pour toujours', en: 'Together forever', es: 'Juntos para siempre' },
  'love.loveStory': { fr: 'Une histoire d\'amour bénie', en: 'A blessed love story', es: 'Una historia de amor bendecida' },
  'love.loveStory.desc': { fr: '___________', en: '___________', es: '___________' },
  'love.countdownLabel': { fr: 'Jours avant notre « Oui, je le veux »', en: 'Days until our "I do"', es: 'Días para nuestro "Sí, acepto"' },
  'love.joinUs': { fr: 'Joignez-vous à notre célébration d\'amour', en: 'Join our celebration of love', es: 'Únete a nuestra celebración de amor' },

  // Footer
  'footer.made': { fr: 'Fait avec amour', en: 'Made with love', es: 'Hecho con amor' },
  'footer.copyright': { fr: '© 2025 Corine & Ruben', en: '© 2025 Corine & Ruben', es: '© 2025 Corine & Ruben' },
  'footer.links': { fr: 'Liens', en: 'Links', es: 'Enlaces' },
  'footer.celebrate': { fr: 'Célébrer', en: 'Celebrate', es: 'Celebrar' },
  'footer.venue': { fr: 'Lieu', en: 'Venue', es: 'Lugar' },

  // 404
  'notfound.title': { fr: 'Page Introuvable', en: 'Page Not Found', es: 'Página No Encontrada' },
  'notfound.desc': { fr: 'Cette page s\'est égarée avant la célébration.', en: 'It seems this page wandered off before the celebration.', es: 'Parece que esta página se perdió antes de la celebración.' },
  'notfound.requested': { fr: 'Demandé', en: 'Requested', es: 'Solicitado' },
  'notfound.returnHome': { fr: 'Retour à l\'accueil', en: 'Return Home', es: 'Volver al Inicio' },
  'notfound.goBack': { fr: 'Retour', en: 'Go Back', es: 'Volver' },
  'notfound.needHelp': { fr: 'Besoin d\'aide ?', en: 'Need help?', es: '¿Necesitas ayuda?' },
  'notfound.reachOut': { fr: 'Contactez les mariés', en: 'Reach out to the couple', es: 'Contacta a los novios' },
  'notfound.contactUs': { fr: 'Nous contacter', en: 'Contact Us', es: 'Contáctanos' },
  'notfound.howWeMet': { fr: 'Notre rencontre', en: 'How we met', es: 'Cómo nos conocimos' },
  'notfound.confirmAttendance': { fr: 'Confirmer présence', en: 'Confirm attendance', es: 'Confirmar asistencia' },
  'notfound.venueSchedule': { fr: 'Lieu & programme', en: 'Venue & schedule', es: 'Lugar y programa' },
  'notfound.backToStart': { fr: 'Retour au début', en: 'Back to the beginning', es: 'Volver al inicio' },

  // Christian / Hymns
  'badge.blessed': { fr: 'Union Bénie', en: 'Blessed Union', es: 'Unión Bendecida' },
  'badge.faith': { fr: 'Foi & Amour', en: 'Faith & Love', es: 'Fe y Amor' },
  'badge.garden': { fr: 'Jardin d\'Éden', en: 'Garden Party', es: 'Fiesta en el Jardín' },
  'badge.covenant': { fr: 'Alliance Sacrée', en: 'Holy Covenant', es: 'Pacto Sagrado' },
  'index.scripture': { fr: 'Écriture', en: 'Scripture', es: 'Escritura' },
  'index.sacredUnion': { fr: 'Union Sacrée', en: 'Sacred Union', es: 'Unión Sagrada' },
  'index.covenantLove': { fr: 'Amour d\'Alliance', en: 'Covenant Love', es: 'Amor de Pacto' },
  'index.foreverAlways': { fr: 'Pour Toujours', en: 'Forever & Always', es: 'Por Siempre' },
  'index.beginJourney': { fr: 'Début du Voyage', en: 'Begin the Journey', es: 'Comienza el Viaje' },
  'index.years': { fr: 'Ans', en: 'Years', es: 'Años' },
  'index.worshipMusic': { fr: 'Musique de Louange', en: 'Worship Music', es: 'Música de Adoración' },
  'index.hymns': { fr: 'Nos Cantiques', en: 'Our Hymns', es: 'Nuestros Himnos' },
  'index.hymns.desc': { fr: 'Les chants qui accompagneront notre célébration', en: 'The songs that will accompany our celebration', es: 'Las canciones que acompañarán nuestra celebración' },
  'hymn.amazing': { fr: 'Grâce Infinie', en: 'Amazing Grace', es: 'Sublime Gracia' },
  'hymn.blessed': { fr: 'Béni Soit le Lien', en: 'Blessed Be the Tie', es: 'Bendito Sea el Lazo' },
  'hymn.howgreat': { fr: 'Que Tu Es Grand', en: 'How Great Thou Art', es: 'Cuán Grande Es Él' },
  'hymn.joyful': { fr: 'Joie au Monde', en: 'Joyful, Joyful', es: 'Alegría, Alegría' },
  'hymn.greatis': { fr: 'Grande Est Ta Fidélité', en: 'Great Is Thy Faithfulness', es: 'Grande Es Tu Fidelidad' },
  'hymn.traditional': { fr: 'Hymne Traditionnel', en: 'Traditional Hymn', es: 'Himno Tradicional' },
  'verse.1cor13': { fr: 'L\'amour est patient, l\'amour est bon. Il n\'envie pas, il ne se vante pas, il ne s\'enfle pas d\'orgueil.', en: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.', es: 'El amor es paciente, es bondadoso. El amor no es envidioso ni jactancioso ni orgulloso.' },
  'verse.1cor13.full': { fr: 'L\'amour est patient, l\'amour est bon. Il ne jalouse pas, il ne se vante pas, il ne s\'enfle pas d\'orgueil. Il ne fait rien de malhonnête, il ne cherche pas son intérêt. Il supporte tout, il croit tout, il espère tout, il endure tout.', en: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking. It always protects, always trusts, always hopes, always perseveres.', es: 'El amor es paciente, es bondadoso. No es envidioso ni jactancioso ni orgulloso. No deshonra a los demás, no es egoísta. Todo lo protege, todo lo cree, todo lo espera, todo lo soporta.' },
  'verse.genesis': { fr: 'C\'est pourquoi l\'homme quittera son père et sa mère, et s\'attachera à sa femme, et ils deviendront une seule chair.', en: 'Therefore a man shall leave his father and his mother and hold fast to his wife, and they shall become one flesh.', es: 'Por eso el hombre dejará a su padre y a su madre, y se unirá a su esposa, y serán una sola carne.' },
  'verse.ecclesiastes': { fr: 'Deux valent mieux qu\'un seul, car ils ont un bon salaire de leur travail. Car s\'ils tombent, l\'un relève son compagnon.', en: 'Two are better than one, because they have a good reward for their toil. For if they fall, one will lift up his fellow.', es: 'Más valen dos que uno solo, porque obtienen más fruto de su esfuerzo. Si caen, el uno levanta al otro.' },
  'verse.proverbs': { fr: 'Confie-toi en l\'Éternel de tout ton cœur, et ne t\'appuie pas sur ta propre intelligence. Reconnais-le dans toutes tes voies, et il aplanira tes sentiers.', en: 'Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.', es: 'Confía en el Señor con todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus sendas.' },
  'verse.colossians': { fr: 'Et par-dessus tout, revêtez-vous de l\'amour, qui est le lien de la perfection.', en: 'And above all these put on love, which binds everything together in perfect harmony.', es: 'Y sobre todas estas cosas, vestíos de amor, que es el vínculo de la perfección.' },
  'verse.romans12': { fr: 'Soyez pleins d\'affection les uns pour les autres dans l\'amour fraternel; rendez-vous honneur les uns aux autres.', en: 'Be devoted to one another in love. Honor one another above yourselves.', es: 'Amaos los unos a los otros con amor fraternal, dándoos preferencia los unos a los otros.' },
  'verse.galatians': { fr: 'Mais le fruit de l\'Esprit, c\'est l\'amour, la joie, la paix, la patience, la bonté, la bienveillance, la fidélité, la douceur, la maîtrise de soi.', en: 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control.', es: 'Pero el fruto del Espíritu es amor, alegría, paz, paciencia, amabilidad, bondad, fidelidad, mansedumbre, dominio propio.' },
  'verse.psalm37': { fr: 'Fais de l\'Éternel tes délices, et il te donnera ce que ton cœur désire.', en: 'Delight yourself in the Lord, and he will give you the desires of your heart.', es: 'Deléitate en el Señor, y él te dará las peticiones de tu corazón.' },
  'verse.section.title': { fr: 'Paroles de Vie', en: 'Words of Life', es: 'Palabras de Vida' },
  'verse.section.subtitle': { fr: 'Les versets qui inspirent notre amour et notre union', en: 'The verses that inspire our love and our union', es: 'Los versículos que inspiran nuestro amor y nuestra unión' },
  'verse.theme.love': { fr: 'Amour', en: 'Love', es: 'Amor' },
  'verse.theme.unity': { fr: 'Unité', en: 'Unity', es: 'Unidad' },
  'verse.theme.bond': { fr: 'Lien Parfait', en: 'Perfect Bond', es: 'Vínculo Perfecto' },
  'verse.theme.marriage': { fr: 'Mariage', en: 'Marriage', es: 'Matrimonio' },
  'verse.theme.devotion': { fr: 'Dévotion', en: 'Devotion', es: 'Devoción' },
  'verse.theme.spirit': { fr: 'Fruit de l\'Esprit', en: 'Fruit of the Spirit', es: 'Fruto del Espíritu' },
  'verse.theme.trust': { fr: 'Confiance', en: 'Trust', es: 'Confianza' },
  'verse.theme.delight': { fr: 'Délice en Dieu', en: 'Delight in God', es: 'Delicia en Dios' },
  'qr.title': { fr: 'Notre Code Personnel', en: 'Our Personal Code', es: 'Nuestro Código Personal' },
  'qr.desc': { fr: 'Scannez ce code pour accéder rapidement à notre page de mariage ou partagez-le avec vos proches.', en: 'Scan this code for quick access to our wedding page or share it with your loved ones.', es: 'Escanea este código para acceder rápidamente a nuestra página de boda o compártelo con tus seres queridos.' },
  'qr.placeholder': { fr: 'QR Code', en: 'QR Code', es: 'Código QR' },
  'qr.hint': { fr: 'Partagez l\'amour — envoyez ce lien à votre famille et vos amis', en: 'Share the love — send this link to your family and friends', es: 'Comparte el amor — envía este enlace a tu familia y amigos' },
  'court.title': { fr: 'Notre Cour Personnelle', en: 'Our Personal Court', es: 'Nuestra Corte Personal' },
  'court.desc': { fr: 'Ce en quoi nous croyons, nos valeurs et les principes qui guident notre union.', en: 'What we believe in, our values, and the principles that guide our union.', es: 'En lo que creemos, nuestros valores y los principios que guían nuestra unión.' },
  'court.belief.love': { fr: 'L\'Amour Inconditionnel', en: 'Unconditional Love', es: 'Amor Incondicional' },
  'court.belief.love.desc': { fr: 'Nous croyons que l\'amour véritable est patient, bienveillant et ne cherche pas son propre intérêt. C\'est le fondement de tout ce que nous construisons ensemble.', en: 'We believe that true love is patient, kind, and does not seek its own interest. It is the foundation of everything we build together.', es: 'Creemos que el amor verdadero es paciente, bondadoso y no busca lo suyo. Es el fundamento de todo lo que construimos juntos.' },
  'court.belief.faith': { fr: 'La Foi Inébranlable', en: 'Unwavering Faith', es: 'Fe Inquebrantable' },
  'court.belief.faith.desc': { fr: 'Notre foi en Dieu est notre ancre. Nous Lui faisons confiance pour guider nos pas et bénir notre chemin ensemble.', en: 'Our faith in God is our anchor. We trust Him to guide our steps and bless our journey together.', es: 'Nuestra fe en Dios es nuestra ancla. Confiamos en Él para guiar nuestros pasos y bendecir nuestro camino juntos.' },
  'court.belief.family': { fr: 'La Famille Unie', en: 'United Family', es: 'Familia Unida' },
  'court.belief.family.desc': { fr: 'Nous valorisons la famille comme un don sacré. Ensemble, nous bâtissons un foyer rempli de joie, de respect et de soutien mutuel.', en: 'We value family as a sacred gift. Together, we build a home filled with joy, respect, and mutual support.', es: 'Valoramos la familia como un don sagrado. Juntos, construimos un hogar lleno de alegría, respeto y apoyo mutuo.' },
  'court.belief.grace': { fr: 'La Grâce & la Gratitude', en: 'Grace & Gratitude', es: 'Gracia y Gratitud' },
  'court.belief.grace.desc': { fr: 'Nous vivons avec grâce et gratitude, reconnaissant chaque bénédiction et choisissant la bonté dans chaque moment.', en: 'We live with grace and gratitude, acknowledging every blessing and choosing kindness in every moment.', es: 'Vivimos con gracia y gratitud, reconociendo cada bendición y eligiendo la bondad en cada momento.' },
  'index.foundedOnFaith': { fr: 'Fondé sur la Foi', en: 'Founded on Faith', es: 'Fundado en la Fe' },
  'index.ceremony': { fr: 'Cérémonie Sacrée', en: 'Sacred Ceremony', es: 'Ceremonia Sagrada' },
  'index.ceremony.desc': { fr: 'Une célébration d\'amour devant Dieu, notre famille et nos amis les plus chers.', en: 'A celebration of love before God, our family, and our dearest friends.', es: 'Una celebración de amor ante Dios, nuestra familia y nuestros amigos más queridos.' },
  'index.blessing': { fr: 'Bénédiction Divine', en: 'Divine Blessing', es: 'Bendición Divina' },
  'index.blessing.desc': { fr: 'Recevant la grâce et la bénédiction de Dieu sur notre union sacrée.', en: 'Receiving God\'s grace and blessing upon our sacred union.', es: 'Recibiendo la gracia y bendición de Dios sobre nuestra unión sagrada.' },
  'index.vows': { fr: 'Vœux Éternels', en: 'Eternal Vows', es: 'Votos Eternos' },
  'index.vows.desc': { fr: 'Des promesses faites devant Dieu, scellées par la foi et l\'amour éternel.', en: 'Promises made before God, sealed by faith and eternal love.', es: 'Promesas hechas ante Dios, selladas por la fe y el amor eterno.' },
  'index.fellowship': { fr: 'Communion Fraternelle', en: 'Fellowship & Joy', es: 'Comunión y Alegría' },
  'index.fellowship.desc': { fr: 'Célébrer ensemble dans la joie, la prière et la reconnaissance.', en: 'Celebrating together in joy, prayer, and gratitude.', es: 'Celebrando juntos con alegría, oración y gratitud.' },

  // Login
  'login.title': { fr: 'Accès Admin', en: 'Admin Access', es: 'Acceso Admin' },
  'login.subtitle': { fr: 'Connectez-vous pour gérer votre tableau de bord', en: 'Sign in to manage your wedding dashboard', es: 'Inicia sesión para administrar tu panel de boda' },
  'login.email': { fr: 'Email', en: 'Email', es: 'Correo' },
  'login.password': { fr: 'Mot de passe', en: 'Password', es: 'Contraseña' },
  'login.submit': { fr: 'Se connecter', en: 'Sign In', es: 'Iniciar Sesión' },
  'login.welcome': { fr: 'Bon retour ! 💕', en: 'Welcome back! 💕', es: '¡Bienvenido de vuelta! 💕' },

  // Dashboard
  'dashboard.admin': { fr: 'Panneau Admin', en: 'Admin Panel', es: 'Panel Admin' },
  'dashboard.title': { fr: 'Tableau de Bord', en: 'Wedding Dashboard', es: 'Panel de Boda' },
  'dashboard.subtitle': { fr: 'Suivez les RSVP, gérez les invités et surveillez les cadeaux.', en: 'Track RSVPs, manage guests, and monitor gifts — all in one place.', es: 'Rastrea RSVP, gestiona invitados y monitorea regalos — todo en un solo lugar.' },
  'dashboard.overview': { fr: 'Aperçu', en: 'Overview', es: 'Resumen' },
  'dashboard.guests': { fr: 'Invités', en: 'Guests', es: 'Invitados' },
  'dashboard.seating': { fr: 'Tables', en: 'Seating', es: 'Asientos' },
  'dashboard.gifts': { fr: 'Cadeaux', en: 'Gifts', es: 'Regalos' },
  'dashboard.totalGuests': { fr: 'Total Invités', en: 'Total Guests', es: 'Total Invitados' },
  'dashboard.families': { fr: '{n} familles', en: '{n} families', es: '{n} familias' },
  'dashboard.confirmed': { fr: 'Confirmés', en: 'Confirmed', es: 'Confirmados' },
  'dashboard.responseRate': { fr: '{n}% taux de réponse', en: '{n}% response rate', es: '{n}% tasa de respuesta' },
  'dashboard.pending': { fr: 'En attente', en: 'Pending', es: 'Pendientes' },
  'dashboard.awaitingResponse': { fr: 'En attente de réponse', en: 'Awaiting response', es: 'Esperando respuesta' },
  'dashboard.totalGifts': { fr: 'Total Cadeaux', en: 'Total Gifts', es: 'Total Regalos' },
  'dashboard.contributions': { fr: '{n} contributions', en: '{n} contributions', es: '{n} contribuciones' },
  'dashboard.rsvpStatus': { fr: 'Statut RSVP', en: 'RSVP Status', es: 'Estado RSVP' },
  'dashboard.declined': { fr: 'Refusés', en: 'Declined', es: 'Rechazados' },
  'dashboard.cuisinePrefs': { fr: 'Préférences de cuisine', en: 'Cuisine Preferences', es: 'Preferencias de Cocina' },
  'dashboard.noMealData': { fr: 'Aucune donnée de repas', en: 'No meal data yet', es: 'Sin datos de comida aún' },
  'dashboard.guestsLabel': { fr: 'invités', en: 'guests', es: 'invitados' },
  'dashboard.recentActivity': { fr: 'Activité Récente', en: 'Recent Activity', es: 'Actividad Reciente' },
  'dashboard.noRsvps': { fr: 'Aucun RSVP — partagez votre lien de mariage !', en: 'No RSVPs yet — share your wedding link!', es: '¡Sin RSVP aún — comparte tu enlace de boda!' },
  'dashboard.searchGuests': { fr: 'Rechercher des invités...', en: 'Search guests...', es: 'Buscar invitados...' },
  'dashboard.guest': { fr: 'Invité', en: 'Guest', es: 'Invitado' },
  'dashboard.partySize': { fr: 'Taille du groupe', en: 'Party Size', es: 'Tamaño del Grupo' },
  'dashboard.status': { fr: 'Statut', en: 'Status', es: 'Estado' },
  'dashboard.cuisine': { fr: 'Cuisine', en: 'Cuisine', es: 'Cocina' },
  'dashboard.table': { fr: 'Table', en: 'Table', es: 'Mesa' },
  'dashboard.message': { fr: 'Message', en: 'Message', es: 'Mensaje' },
  'dashboard.noGuests': { fr: 'Aucun invité trouvé', en: 'No guests found', es: 'No se encontraron invitados' },
  'dashboard.tablesAssigned': { fr: '{used} de {total} tables assignées · {guests} invités placés', en: '{used} of {total} tables assigned · {guests} guests seated', es: '{used} de {total} mesas asignadas · {guests} invitados sentados' },
  'dashboard.ofSeats': { fr: 'de {n} places', en: 'of {n} seats', es: 'de {n} asientos' },
  'dashboard.totalReceived': { fr: 'Total Reçu', en: 'Total Received', es: 'Total Recibido' },
  'dashboard.contributors': { fr: 'Contributeurs', en: 'Contributors', es: 'Contribuyentes' },
  'dashboard.averageGift': { fr: 'Cadeau Moyen', en: 'Average Gift', es: 'Regalo Promedio' },
  'dashboard.from': { fr: 'De', en: 'From', es: 'De' },
  'dashboard.amount': { fr: 'Montant', en: 'Amount', es: 'Monto' },
  'dashboard.date': { fr: 'Date', en: 'Date', es: 'Fecha' },
  'dashboard.noGifts': { fr: 'Aucun cadeau', en: 'No gifts yet', es: 'Sin regalos aún' },
  'dashboard.giftTiers': { fr: 'Niveaux de Cadeaux', en: 'Gift Tiers', es: 'Niveles de Regalos' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('wedding-lang');
    return (saved === 'en' || saved === 'fr' || saved === 'es') ? saved : 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('wedding-lang', lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
